### ISSUE TITLE
Menu not filtering on Firefox Android

### ISSUE THREAD

**Issue by kittsville** [The-Silverwood-Institute/Frontend#10]
The menu should filter as the input's being typed. This is not happening on Firefox for Android:
![screenshot_20181209-192855](https://user-images.githubusercontent.com/6013087/49701871-8ad58180-fbe9-11e8-8c42-9ddccd024b3e.jpg)

Bug is because `keydown` and `keyup` events aren't firing: Pixabay/JavaScript-autoComplete#71. Replacing the non-firing events with `input` should fix everything.

**Comment by JeyanthVictory** [comment]
@kittsville ,Your solution works only when the input has some value. Consider, if I want to manipulate something on deleting the input when it has no value. In that case, input won't trigger. What I'm supposed to do then?

**Comment by kittsville** [comment]
That's beyond my use case so I'm not concerned.
